environment: production
http_port: 8888
grpc_port: 8889
auth_secret: ######

database_uri: postgres://postgres:QuocAnh-1809@localhost:5432/gohub

redis_uri: localhost:6379
redis_password:
redis_db: 0
